---
# YAML format inventory with nested groups for variable inheritance
# Mason Morales, Splunk, Inc.
# References:
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# Read this: https://docs.ansible.com/ansible/2.9/plugins/inventory/yaml.html
# https://www.digitalocean.com/community/tutorials/how-to-manage-multistage-environments-with-ansible
# ##########################################################################
all:
  hosts:
    splunk-sd:
      ansible_port: 22
      ansible_host: 10.10.0.50
    splunk-cm:
      ansible_port: 22
      ansible_host: 10.10.0.51
    splunk-idx1:
      ansible_port: 22
      ansible_host: 10.10.0.52
    splunk-idx2:
      ansible_port: 22
      ansible_host: 10.10.0.53
    splunk-idx3:
      ansible_port: 22
      ansible_host: 10.10.0.54
    splunk-sh1:
      ansible_port: 22
      ansible_host: 10.10.0.55
    splunk-sh2:
      ansible_port: 22
      ansible_host: 10.10.0.56
    splunk-sh3:
      ansible_port: 22
      ansible_host: 10.10.0.57
    splunk:
      ansible_port: 22
      ansible_host: 10.10.0.58
    splunk-hf:
      ansible_port: 22
      ansible_host: 10.10.0.59
    splunk-audit:
      ansible_port: 22
      ansible_host: 10.10.0.60
  children:
    full:
      children:
        licensemaster:
          hosts:
            splunk-sd:
          vars:
            splunk_license_file: [ Splunk5M.lic ]
            splunk_license_group: Enterprise
        deploymentserver:
          hosts:
            splunk-sd:
        dmc:
          hosts:
            splunk-sd:
          vars:
            splunk_uri_cm: https://splunk-cm:8089
        shdeployer:
          hosts:
            splunk-sd:
          vars:
            target_shc_group_name: nemesis4shc
            splunk_shc_target_group: nemesis4shc

        clustermanager:
          hosts:
            splunk-cm:
          vars:
            splunk_license_group: Peer

        indexer:
          children:
            nemesis4_idxc:
              hosts:
                splunk-idx1:
                splunk-idx2:
                splunk-idx3:
          vars:
            splunk_license_group: Peer
            splunk_uri_cm: https://splunk-cm:8089

        search:
          children:
            nemesis4shc:
              hosts:
                splunk-sh1:
                splunk-sh2:
                splunk-sh3:
          vars:
            splunk_license_group: Peer
            splunk_uri_cm: https://splunk-cm:8089

        heavyForwarder:
          hosts:
            splunk-hf:

        standalone:
            hosts:
              splunk-audit:

    #uf:
    #  children:
    #   vmware:
    #     hosts:
    #       my-vm-ware-host-[001:100]:
    #     vars:
    #       clientName: vmware # Or create a "vmware.yml" file under group_vars and assign clientName there, either works

    #   web:
    #     hosts:
    #       my-web-host-[01-05]:
