---
- name: Configure custom login content
  block:
    - name: Configure custom login content using inventory_hostname
      ini_file:
        path: "{{ splunk_home }}/etc/system/local/web.conf"
        section: settings
        option: login_content
        value: "<h1>{{ inventory_hostname }}</h1>"
        owner: "{{ splunk_nix_user }}"
        group: "{{ splunk_nix_group }}"
        mode: 0644
      become: true
      notify: restart splunk
      when:
        - inventory_hostname == ansible_host
    - name: Configure custom login content using both inventory_hostname and ansible_host
      ini_file:
        path: "{{ splunk_home }}/etc/system/local/web.conf"
        section: settings
        option: login_content
        value: "<h1>{{ inventory_hostname }} - {{ ansible_host }}</h1>"
        owner: "{{ splunk_nix_user }}"
        group: "{{ splunk_nix_group }}"
        mode: 0644
      become: true
      notify: restart splunk
      when:
        - inventory_hostname != ansible_host
  when:
    - customize_login_content == True
