---
##off##- name: Set timezone to Europe/Rome
##off##  timezone:
##off##    name: Europe/Rome

- name: Update /etc/hosts
  include_tasks: 5m_configure_hosts.yml

- name: Configure SSH keys
  include_tasks: 5m_ssh.yml
