---
splunk_uri_lm: https://splunk-cm.5minfo.it:8089
#splunk_uri_ds: https://splunk-sd.5minfo.it:8089
ansible_user: splunk
ansible_ssh_private_key_file: ~/.ssh/id_rsa
splunk_create_polkit: 1
splunk_use_initd: false
splunk_use_systemd: true
configure_firewall: true
firewall_service: "firewalld"
