---
- hosts: splunk-lbhf,splunk-lbshc
  become: true

  tasks:
    - name: Install nginx
      when:
        - ansible_os_family == 'Debian'
      block:
        - name: Install aptitude
          apt:
            name: aptitude
            state: latest
            update_cache: true

        - name: Install required system packages
          apt:
            pkg:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
              - python3-pip
              - virtualenv
              - python3-setuptools
            state: latest
            update_cache: false

        - name: Install nginx
          apt:
            name: nginx
            state: latest
            update_cache: false

        - name: Create DHParam
          #when: 1==0
          shell:
            creates: /etc/nginx/dhparam.pem
            cmd: openssl dhparam -out /etc/nginx/dhparam.pem 4096

        - name: Copy certificate and key LBHF
          #when: ansible_hostname == "splunk-lbhf"
          copy:
            src: "../roles/splunk/files/{{ item }}"
            dest: "/etc/ssl/private/{{ item }}"
            owner: root
            group: root
            mode: '0644'
          loop:
            - "{{ ansible_hostname }}.cert.pem"
            - "{{ ansible_hostname }}.key.pem"

        - name: Prepare SSL Snippet
          copy:
            dest: "/etc/nginx/snippets/certificate.conf"
            content: |
              ssl_certificate /etc/ssl/private/{{ ansible_hostname }}.cert.pem;
              ssl_certificate_key /etc/ssl/private/{{ ansible_hostname}}.key.pem;

        - name: Prepare SSL Param Snippet
          copy:
            dest: "/etc/nginx/snippets/ssl-params.conf"
            content: |
              ssl_protocols             TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              ssl_dhparam               /etc/nginx/dhparam.pem;
              ssl_ciphers               EECDH+AESGCM:EDH+AESGCM;
              ssl_ecdh_curve            secp384r1;
              ssl_session_timeout       10m;
              ssl_session_cache         shared:SSL:10m;
              ssl_session_tickets       off;
              ssl_stapling              on;
              ssl_stapling_verify       on;
              #resolver 8.8.8.8 8.8.4.4 valid=300s;
              #resolver_timeout 5s;
              # Disable strict transport security for now. You can uncomment the following
              # line if you understand the implications.
              #add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
              #add_header X-Frame-Options DENY;
              #add_header X-Content-Type-Options nosniff;
              #add_header X-XSS-Protection "1; mode=block";

        - name: remove default site synlink
          file:
            path: /etc/nginx/sites-enabled/default
            state: absent
            follow: false

        - name: Prepare available site WEB
          when: ansible_hostname == "splunk-lbshc"
          copy:
            dest: "/etc/nginx/sites-available/splunk-lbshc"
            content: |
              upstream splunk_web {
                    ip_hash;
                    server splunk-sh1:8000;
                    server splunk-sh2:8000;
                    server splunk-sh3:8000;
              }
              server {
                      listen 80 default_server;
                      return 301 https://$host$request_uri;
              }
              server {
                      listen 443 ssl default_server;
                      gzip off;
                      #
                      # Read up on ssl_ciphers to ensure a secure configuration.
                      # See: https://bugs.debian.org/765782
                      #
                      include snippets/certificate.conf;
                      include snippets/ssl-params.conf;

                      server_name _;

                      location / {
                              #proxy_pass                 https://splunk_ds_on_hf;
                              proxy_pass                 https://splunk_web/;
                              proxy_read_timeout         90s;
                              proxy_connect_timeout      90s;
                              proxy_send_timeout         90s;
                              proxy_redirect             off;
                              proxy_set_header           Host              $host;
                              proxy_set_header           X-Real-IP         $remote_addr;
                              proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
                              proxy_set_header           X-Forwarded-Proto $scheme;
                              proxy_set_header           X-Forwarded-Host  $host;
                              proxy_set_header           X-Forwarded-Port  $server_port;
                              proxy_set_header           Proxy             "";
                              proxy_pass_request_headers on;
                              proxy_ssl_verify           off;
                      }
              }

        - name: Prepare available site DS
          when: ansible_hostname == "splunk-lbhf"
          copy:
            dest: "/etc/nginx/sites-available/splunk-lbhf_ds"
            content: |
              upstream splunk_ds_on_hf {
                    ip_hash;
                    server splunk-forwarder1:8089;
                    server splunk-forwarder2:8089;
                    server splunk-forwarder3:8089;
              }
              server {
                      listen 8089 ssl default_server;
                      gzip off;
                      #
                      # Read up on ssl_ciphers to ensure a secure configuration.
                      # See: https://bugs.debian.org/765782
                      #
                      include snippets/certificate.conf;
                      include snippets/ssl-params.conf;

                      server_name _;

                      location / {
                              proxy_pass                 https://splunk_ds_on_hf;
                              proxy_read_timeout         90s;
                              proxy_connect_timeout      90s;
                              proxy_send_timeout         90s;
                              proxy_redirect             off;
                              proxy_set_header           Host              $host;
                              proxy_set_header           X-Real-IP         $remote_addr;
                              proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
                              proxy_set_header           X-Forwarded-Proto $scheme;
                              proxy_set_header           X-Forwarded-Host  $host;
                              proxy_set_header           X-Forwarded-Port  $server_port;
                              proxy_set_header           Proxy             "";
                              proxy_pass_request_headers on;
                              proxy_ssl_verify           off;
                      }
              }

        - name: Prepare available site HEC
          when: ansible_hostname == "splunk-lbhf"
          copy:
            dest: "/etc/nginx/sites-available/splunk-lbhf_hec"
            content: |
              upstream splunk_hec_on_idx {
                    keepalive 32;
                    server splunk-indexer1:8088;
                    server splunk-indexer2:8088;
              }
              server {
                      listen 8088 ssl default_server;
                      gzip off;
                      #
                      # Read up on ssl_ciphers to ensure a secure configuration.
                      # See: https://bugs.debian.org/765782
                      #
                      include snippets/certificate.conf;
                      include snippets/ssl-params.conf;

                      server_name _;

                      location / {
                              proxy_pass                 https://splunk_hec_on_idx;
                              proxy_set_header           Connection             "";
                              proxy_http_version         1.1;
                              proxy_ssl_verify           off;
                      }
              }

        - name: Create symlink in sites-enabled LBSHC
          when: ansible_hostname == "splunk-lbshc"
          file:
            path: /etc/nginx/sites-enabled/splunk-lbshc
            state: link
            src: /etc/nginx/sites-available/splunk-lbshc

        - name: Create symlink in sites-enabled LBHF for DS
          when: ansible_hostname == "splunk-lbhf"
          file:
            path: /etc/nginx/sites-enabled/splunk-lbhf_ds
            state: link
            src: /etc/nginx/sites-available/splunk-lbhf_ds

        - name: Create symlink in sites-enabled LBHF for HEC
          when: ansible_hostname == "splunk-lbhf"
          file:
            path: /etc/nginx/sites-enabled/splunk-lbhf_hec
            state: link
            src: /etc/nginx/sites-available/splunk-lbhf_hec

        - name: Check NGINX configuration
          when: ansible_hostname == "splunk-lbhf" or ansible_hostname == "splunk-lbshc"
          shell:
            cmd: nginx -t

        - name: Enable and Start NGINX
          when: ansible_hostname == "splunk-lbhf" or ansible_hostname == "splunk-lbshc"
          systemd:
            name: nginx
            enabled: true
            state: restarted
