#- hosts:
#    - full
#  roles:
#    - ../roles/splunk
#  vars:
#    - deployment_task: 5m_configure_hosts.yml

- hosts:
    - licensemaster
    - dmc
    - clustermanager
    - indexer
    - shc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: check_splunk.yml

- hosts:
    - all
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_systemd.yml

- hosts:
    - clustermanager
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_idxc_manager.yml

- hosts:
    - indexer
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_idxc_member.yml

- hosts:
    - shdeployer
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_shc_deployer.yml

- hosts:
    - shc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_shc_members.yml

- hosts:
    - shc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_shc_captain.yml

- hosts:
    - dmc
  roles:
    - ../roles/splunk
  vars:
    - deployment_task: configure_dmc.yml

